name: gaussian_grouping2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.2.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - tqdm
  - scipy
  - opencv
  - scikit-learn
  - pip:
    - plyfile==0.8.1
    - lpips
    - wandb
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn